    CC     = gcc -std=c11 -pg 
    LFLAGS =

      PROG = cgSolver
      OBJS = utils.o \
             geraMat.o \
             validateEntry.o \
             gradients.o \
             $(PROG).o

    LIKWID = /home/soft/likwid
	LIKWID_FLAGS = -I$(LIKWID)/include
	LIKWID_LIBS = -L$(LIKWID)/lib

	AVX_FLAGS = -march=native -mavx -O3 -falign-functions=32 -falign-loops=32 -fstrict-aliasing
	AVX_LOG_FLAGS = -fopt-info-vec -fopt-info-vec-missed 
	
       CFLAGS = $(LIKWID_FLAGS) 
       LFLAGS = $(LIKWID_LIBS) -lm

.PHONY: limpa faxina clean distclean purge all avx likwid

%.o: %.c %.h utils.h
	$(CC) -c $(CFLAGS) $<

$(PROG):  $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^ $(LFLAGS)
	
all: $(PROG) doc
	
doc: Doxyfile
	doxygen $<
	
avx:           CFLAGS += $(AVX_FLAGS) $(AVX_LOG_FLAGS)
avx likwid:    CFLAGS += -DLIKWID_PERFMON
avx likwid:    LFLAGS += -llikwid

Doxyfile:
	doxygen -g
	sed -e "s;OPTIMIZE_OUTPUT_FOR_C *= *.*;OPTIMIZE_OUTPUT_FOR_C = YES;g" $@ >$@.new
	sed -e "s;EXTRACT_ALL *= *.*;EXTRACT_ALL = YES;g" $@.new >$@
	sed -e "s;EXTRACT_PRIVATE *= *.*;EXTRACT_PRIVATE = YES;g" $@ >$@.new
	sed -e "s;EXTRACT_STATIC *= *.*;EXTRACT_STATIC = YES;g" $@.new >$@
	sed -e "s;EXTRACT_LOCAL_METHODS *= *.*;EXTRACT_LOCAL_METHODS = YES;g" $@ >$@.new
	sed -e "s;GENERATE_LATEX *= *.*;GENERATE_LATEX = NO;g" $@.new >$@
	sed -e "s;SOURCE_BROWSE *= *.*;SOURCE_BROWSE = YES;g" $@ >$@.new
	sed -e "s;VERBATIM_HEADER *= *.*;VERBATIM_HEADER = YES;g" $@.new >$@
	rm -f $@.new
	
clean:
	rm -rf *~ *.bak

purge: clean
	rm -rf Doxyfile html latex
	rm -f *.o $(PROG)
